### ISSUE TITLE
达达，我对MiniCMS进行了二次开发并发布在了Github上

### ISSUE THREAD

**Issue by Tokinx** [bg5sbk/MiniCMS#10]
是这样的，真的很喜欢这款程序，很简洁，但是有一些喜爱的功能它并不支持，我对MiniCMS进行了二次开发，并发布在了Github上，在这里通知您一声，如果因为某些原因侵犯了您的权益，您可以在Github上联系我，我会及时删除相关代码。

新的项目地址在：https://github.com/Tokinx/McBlog

它的演示地址是：http://hi.idevs.cn

再次感谢MiniCMS

**Comment by idada** [comment]
:+1:
