### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by comp20141117** [bg5sbk/MiniCMS#11]
不好意思，在您的github下没有找到install.php的文件，直接进入主页面之后显示
创建配置文件失败，创建文章索引目录失败，创建页面索引目录失败
在您的网站中下载了install.php后，显示
解压install.txt失败
是什么原因呢

**Comment by bg5sbk** [comment]
从这里下载：https://github.com/bg5sbk/MiniCMS/releases

把install.php传到服务器上，用浏览器访问install.php就可以，会自动解压缩其他文件到网站目录。
